version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - es_network
    restart: always  # Ensures Elasticsearch runs continuously

  fastapi-app:
    build: .
    container_name: fastapi-app
    volumes:
      - ./classEngine:/app  # Mounts classEngine source code
    working_dir: /app  # Ensures the working directory is correct
    depends_on:
      - elasticsearch
    ports:
      - "8000:8000"
    networks:
      - es_network
    restart: "no"  # Prevents automatic restart; manual start/stop

networks:
  es_network:
    driver: bridge
