version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD} # Use variable from .env
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - es_network
    restart: always

  fastapi-app:
    build: .
    container_name: fastapi-app
    volumes:
      - ./classEngine:/app
    working_dir: /app
    depends_on:
      - elasticsearch
    ports:
      - "8000:8000"
    networks:
      - es_network
    environment:
      - ELASTICSEARCH_USER=${ELASTICSEARCH_USER} # Use variable from .env
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD} # Use variable from .env
    restart: "no"

networks:
  es_network:
    driver: bridge