version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  fastapi-app:
    build: .
    container_name: fastapi-app
    volumes:
      - ./classEngine:/app  # Mounts the FastAPI source code directory
    working_dir: /app
    depends_on:
      - elasticsearch
    ports:
      - "8000:8000"  # Expose FastAPI service
    networks:
      - es_network

networks:
  es_network:
    driver: bridge